sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.7.*

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: SYMFONY_VERSION=2.7.*

  include:
    - php: 5.5
      env:
        - SYMFONY_VERSION=2.7.*
        - EXECUTE_CS_CHECK=true

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update
  - composer require --dev --no-update symfony/symfony:${SYMFONY_VERSION}

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then vendor/bin/php-cs-fixer fix -v --dry-run; fi
