sudo: false

language: php


env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
    - php: 7
    - php: hhvm

before_install:
  - composer require --dev --no-update symfony/symfony:${SYMFONY_VERSION}

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then vendor/bin/php-cs-fixer fix -v --dry-run; fi
